platform :ios, '7.0'
pod 'BlocksKit', '~> 2.2.5'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~> 3.7.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'iCarousel', '~> 1.8.1'
pod 'MJExtension', '~> 2.5.3'
pod 'Masonry', '~> 0.6.2'
pod 'DKNightVersion', '~> 0.8.1'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MJRefresh', '~> 3.0.4'
pod 'SECoreTextView', '~> 0.8.5'
pod 'Bugtags', '~> 1.1.3'
pod 'GPUImage', '~> 0.1.7'
pod 'CWStatusBarNotification', '~> 2.3.3'
pod 'SDCycleScrollView', '~> 1.3'
pod 'CocoaLumberjack'
pod 'MYBlurIntroductionView'
pod 'ChameleonFramework'
pod 'FMDB'
#pod 'CZWeatherKit'
pod 'Mantle'


